from django.urls import path
from .views import *
from . import views
from . import seo_views

urlpatterns = [
    path('categories/', category_list),
    path('live-updates/', views.live_updates_api, name='api_live_updates'),
    path('newsletters/', views.newsletters_api, name='api_newsletters'),
    path('newsletters', views.newsletters_api, name='api_newsletters_no_slash'),
    path('newsletters/<int:newsletter_id>/', views.newsletter_detail_api, name='api_newsletter_detail'),
    path('articles/', article_list),
    path('articles/<int:pk>/review-action/<str:action>/', views.article_review_email_action, name='article_review_email_action'),
    path('articles/<int:pk>/', views.article_detail),
    path('articles/slug/<slug:slug>/', views.article_detail_by_slug, name='api_article_by_slug'),
    path('render/article/<slug:slug>/', seo_views.api_render_article_html, name='api_render_article_html'),
    path('render/article/<slug:category_slug>/<slug:slug>/', seo_views.api_render_article_html, name='api_render_article_html_with_category'),
    path('articles/by-state/', views.articles_by_state),
    path('dashboard/stats/', views.dashboard_stats_api, name='api_dashboard_stats'),
    path('contact-queries/', views.contact_query_create, name='api_contact_query_create'),
    path('career-applications/', views.career_application_create, name='api_career_application_create'),
    path('jobs/', views.job_openings_list, name='api_job_openings'),
    path('weather/', weather_api),
    path('football/leagues/', views.football_leagues_api, name='api_football_leagues'),
    path('football/fixtures/', views.football_fixtures_api, name='api_football_fixtures'),
    path('football/standings/', views.football_standings_api, name='api_football_standings'),
    path('football/overview/', views.football_overview_api, name='api_football_overview'),
    path('metal-ticker/', metal_ticker),
    path('update-metal/', update_metal_rates),
    path('market-indices/', market_indices),
    path('datetime/', datetime_api, name='api-datetime'),
    path('search/', search_api, name='api-search'),
    path('search/articles/', live_article_search_api, name='api-live-article-search'),
    path('search/categories/', live_category_search_api, name='api-live-category-search'),
    path('login/',          views.secure_login_view,  name='login'),
    path('logout/',         views.secure_logout_view, name='logout'),
    path('my-credentials/', views.my_credentials,     name='my_credentials'),

    path('ai/humanize/',         views.ai_humanize_article,  name='ai_humanize_article'),
    path('ai/grammar-check/',    views.ai_grammar_check,     name='ai_grammar_check'),   
    path('ai/sentence-suggestions/', views.ai_sentence_suggestions, name='ai_sentence_suggestions'),
    path('ai/plagiarism-check/', views.ai_plagiarism_check,  name='ai_plagiarism_check'),
    path('ai/seo-keywords/',     views.ai_seo_keywords,      name='ai_seo_keywords'),
    path('ai/translate/',        views.ai_translate,         name='ai_translate'),

    path('categories/create/',                 category_create,  name='api_category_create'),
    path('categories/<int:cat_id>/update/',    category_update,  name='api_category_update'),
    path('categories/<int:cat_id>/archive/',   category_archive, name='api_category_archive'),
    path('categories/<int:cat_id>/restore/',   category_restore, name='api_category_restore'),
    path('categories/<int:cat_id>/subcategories/archive/', views.category_subcategory_archive, name='api_category_subcategory_archive'),
    path('categories/<int:cat_id>/subcategories/restore/', views.category_subcategory_restore, name='api_category_subcategory_restore'),
    path('categories/<int:cat_id>/posts/',     category_posts,   name='api_category_posts'),
    path('media/photos/', media_photos_api, name='media_photos_api'),
    path('media/videos/', media_videos_api, name='media_videos_api'),
    path('media/inline-image/', views.inline_image_upload, name='inline_image_upload'),
    path('media/crop-image/', views.crop_image_api, name='crop_image_api'),
    path('notifications/<int:id>/read/',      views.mark_notification_read, name='api_notification_read'),
    path('notifications/<int:id>/archive/',   views.archive_notification,   name='api_notification_archive'),
    path('notifications/<int:id>/unarchive/', views.unarchive_notification, name='api_notification_unarchive'),
    path('notifications/mark-all-read/', views.mark_all_notifications_read, name='api_notification_mark_all_read'),
    path('notifications/status/', views.notification_status_api, name='api_notification_status'),
    path('attendance/status/', views.attendance_status_api, name='attendance_status'),
    path('attendance/clock-in/', views.attendance_clock_in_api, name='attendance_clock_in'),
    path('attendance/email-action/', views.attendance_email_action, name='attendance_email_action'),
    path('attendance/heartbeat/', views.attendance_heartbeat_api, name='attendance_heartbeat'),
    path('attendance/disconnect/', views.attendance_disconnect_api, name='attendance_disconnect'),
    path('leaves/email-action/', views.leave_request_email_action, name='leave_request_email_action'),
    path('admin/online-status/', online_status_view, name='online_status'),
    path('live-cricket/', live_cricket),
    path('settings/tag-creation-perm/', views.save_tag_creation_perm, name='save_tag_perm'),
    path('homepage/hero/',        views.update_hero_slot,        name='hp_hero'),
    path('homepage/hero/current/', views.homepage_hero_current,  name='hp_hero_current'),
    path('homepage/latest_news/', views.update_latest_news_slot, name='hp_latest'),
    path('homepage/latest_news/current/', views.homepage_latest_news_current, name='hp_latest_current'),
    path('homepage/ad_banner/',   views.update_ad_slot,          name='hp_ad'),
    path('homepage/ad_banner/current/', views.homepage_ad_banner, name='hp_ad_current'),
    path('homepage/ad_banner/library/', views.saved_ad_banner_library, name='hp_ad_library'),
    path('homepage/ad_banner/library/save/', views.save_ad_banner_library_item, name='hp_ad_library_save'),
    path('homepage/ad_banner/library/<int:banner_id>/rename/', views.rename_saved_ad_banner, name='hp_ad_library_rename'),
    path('homepage/ad_banner/library/<int:banner_id>/delete/', views.delete_saved_ad_banner, name='hp_ad_library_delete'),
    path('admin/media-library/', media_library_view, name='admin_media_library'),
    path('newsletter/send/', views.send_newsletter, name='newsletter_send'),
    path('newsletter/subscribe/', views.subscribe_newsletter, name='newsletter_subscribe'),
    path('newsletter/history/', views.newsletter_history, name='newsletter_history'),
    path('newsletter/brevo-webhook/', views.newsletter_brevo_webhook, name='newsletter_brevo_webhook'),

    # ── Web Push Notifications ──
    path('push/subscribe/', views.save_push_subscription, name='push_subscribe'),
    path('push/vapid-key/', views.get_vapid_public_key,   name='push_vapid_key'),
    path('push/status/', views.push_delivery_status, name='push_status'),
    path('push/test/', views.send_test_push_notification, name='push_test'),
    path('messages/edit/', views.edit_message, name='message_edit'),
    path('messages/delete/', views.delete_message, name='message_delete'),
]

