"""
Django settings for news project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import base64
from pathlib import Path
from dotenv import load_dotenv

from google.oauth2 import service_account

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')
load_dotenv()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
import os
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-7uf(u#&rj5=7ewa&5qt@9$c1*nlg^09f$hyd7t+@0)fr&+ft5p')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'https://news4bharat.cloud',
    'https://www.news4bharat.cloud',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]

VIDEO_CONFERENCE_DOMAIN = os.environ.get('VIDEO_CONFERENCE_DOMAIN', 'meet.jit.si').strip().strip('/')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'newsapp',
    'storages', 
    'django.contrib.sitemaps',
    'django_crontab',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'newsapp.middleware.ActiveUserMiddleware',

]

ROOT_URLCONF = 'news.urls'

import os

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':  [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'news.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'news4bharat',
        'USER': 'news4bharat_user',
        'PASSWORD': 'News@4Bharat#2026',
        'HOST': '187.127.135.32',
        'PORT': '5432',
        'OPTIONS': {
            'connect_timeout': 10,
            'keepalives': 1,
            'keepalives_idle': 30,
            'keepalives_interval': 10,
            'keepalives_count': 5,
        },
        'CONN_MAX_AGE': 60,
        'CONN_HEALTH_CHECKS': True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

CORS_ALLOWED_ORIGINS = [
    "https://news4bharat.cloud",
    "https://www.news4bharat.cloud",
    "https://www.news4bharat.com",
    "https://news4bharat.com",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
]
CORS_PREFLIGHT_MAX_AGE = 3600

DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

OPENWEATHER_API_KEY = os.environ.get("OPENWEATHER_API_KEY", "")
METAL_API_KEY = os.environ.get("METAL_API_KEY", "")
TWELVE_DATA_API_KEY = os.environ.get("TWELVE_DATA_API_KEY", "")
ALPHA_VANTAGE_API_KEY = os.environ.get("ALPHA_VANTAGE_API_KEY", "")
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "").strip()
OPENAI_MODEL = os.environ.get("OPENAI_MODEL", "gpt-5.4-mini").strip()
TWELVE_DATA_GOLD_SYMBOLS = ["XAU/USD", "XAUUSD"]
TWELVE_DATA_SILVER_SYMBOLS = ["XAG/USD", "XAGUSD"]
TWELVE_DATA_USDINR_SYMBOLS = ["USD/INR", "USDINR"]
TWELVE_DATA_NIFTY_SYMBOLS = [
    {"symbol": "NIFTYBEES", "exchange": "NSE"},
    {"symbol": "SETFNIF50", "exchange": "NSE"},
]
TWELVE_DATA_SENSEX_SYMBOLS = [
    {"symbol": "SENSEXETF", "exchange": "NSE"},
    {"symbol": "LICNETFSEN", "exchange": "NSE"},
]
ALPHA_VANTAGE_NIFTY_SYMBOLS = ["NIFTYBEES.BSE", "NIFTYBEES.NSE"]
ALPHA_VANTAGE_SENSEX_SYMBOLS = ["SENSEXBEES.BSE", "SENSEXBEES.NSE"]
CRICKET_API_KEY = os.getenv("CRICKET_API_KEY")
FOOTBALL_API_KEY = os.environ.get("FOOTBALL_API_KEY", "").strip()
DIGILOCKER_CLIENT_ID = os.environ.get("DIGILOCKER_CLIENT_ID", "").strip()
DIGILOCKER_CLIENT_SECRET = os.environ.get("DIGILOCKER_CLIENT_SECRET", "").strip()
DIGILOCKER_REDIRECT_URI = os.environ.get("DIGILOCKER_REDIRECT_URI", "").strip()
DIGILOCKER_AUTH_URL = os.environ.get("DIGILOCKER_AUTH_URL", "").strip()
DIGILOCKER_TOKEN_URL = os.environ.get("DIGILOCKER_TOKEN_URL", "").strip()
DIGILOCKER_USERINFO_URL = os.environ.get("DIGILOCKER_USERINFO_URL", "").strip()
DIGILOCKER_DOCUMENTS_URL = os.environ.get("DIGILOCKER_DOCUMENTS_URL", "").strip()
DIGILOCKER_SCOPE = os.environ.get("DIGILOCKER_SCOPE", "").strip()

CRONJOBS = [
    ('*/1 * * * *', 'newsapp.scheduling.publish_due_articles_cron'),
    ('*/1 * * * *', 'newsapp.attendance_reminders.process_attendance_reminders_cron'),
]

FRONTEND_BUILD_HOOK_URL = os.environ.get("FRONTEND_BUILD_HOOK_URL", "")
FRONTEND_BUILD_HOOK_TOKEN = os.environ.get("FRONTEND_BUILD_HOOK_TOKEN", "")
FRONTEND_BUILD_HOOK_TIMEOUT = int(os.environ.get("FRONTEND_BUILD_HOOK_TIMEOUT", "10"))
FRONTEND_BUILD_EVENT_PUBLISHED = os.environ.get(
    "FRONTEND_BUILD_EVENT_PUBLISHED",
    "article-published",
)
FRONTEND_BUILD_EVENT_UPDATED = os.environ.get(
    "FRONTEND_BUILD_EVENT_UPDATED",
    "article-updated",
)
FRONTEND_BUILD_EVENT_FALLBACK = os.environ.get(
    "FRONTEND_BUILD_EVENT_FALLBACK",
    "rebuild-frontend",
)
FRONTEND_BUILD_MODE = os.environ.get("FRONTEND_BUILD_MODE", "hook").strip().lower()
FRONTEND_PRERENDER_BASE_URL = os.environ.get("FRONTEND_PRERENDER_BASE_URL", "https://news4bharat.com").rstrip("/")
FRONTEND_PRERENDER_OUTPUT_DIR = os.environ.get("FRONTEND_PRERENDER_OUTPUT_DIR", "/tmp/prerender_output/__prerender")
FRONTEND_PRERENDER_MAX_ATTEMPTS = int(os.environ.get("FRONTEND_PRERENDER_MAX_ATTEMPTS", "3"))
FRONTEND_PRERENDER_TIMEOUT_MS = int(os.environ.get("FRONTEND_PRERENDER_TIMEOUT_MS", "30000"))
FRONTEND_PRERENDER_SETTLE_MS = int(os.environ.get("FRONTEND_PRERENDER_SETTLE_MS", "10000"))
FRONTEND_PRERENDER_READY_SELECTOR = os.environ.get(
    "FRONTEND_PRERENDER_READY_SELECTOR",
    'meta[name="prerender-status-code"][content]',
).strip()
FRONTEND_PRERENDER_SUCCESS_STATUS = os.environ.get("FRONTEND_PRERENDER_SUCCESS_STATUS", "200").strip()
FRONTEND_PRERENDER_NON_RETRY_STATUSES = tuple(
    status.strip()
    for status in os.environ.get("FRONTEND_PRERENDER_NON_RETRY_STATUSES", "404,500").split(",")
    if status.strip()
)
FRONTEND_PRERENDER_REMOTE_USER = os.environ.get("FRONTEND_PRERENDER_REMOTE_USER", "").strip()
FRONTEND_PRERENDER_REMOTE_HOST = os.environ.get("FRONTEND_PRERENDER_REMOTE_HOST", "").strip()
FRONTEND_PRERENDER_REMOTE_PORT = os.environ.get("FRONTEND_PRERENDER_REMOTE_PORT", "22").strip()
FRONTEND_PRERENDER_REMOTE_PATH = os.environ.get("FRONTEND_PRERENDER_REMOTE_PATH", "").strip()
FRONTEND_PRERENDER_SSH_KEY = os.environ.get("FRONTEND_PRERENDER_SSH_KEY", "").strip()
FRONTEND_PRERENDER_LOG_FILE = os.environ.get("FRONTEND_PRERENDER_LOG_FILE", "").strip()
FRONTEND_PRERENDER_LOCK_DIR = os.environ.get("FRONTEND_PRERENDER_LOCK_DIR", "").strip()


# ── Elasticsearch Connection ─────────────────────────────────────────
# ELASTICSEARCH_DSL = {
#     'default': {
#         'hosts': 'http://localhost:9200',   # default ES port

#         # Agar ES 8.x use kar rahe ho aur security enabled hai:
#         # 'http_auth': ('elastic', 'your_password'),
#         # 'use_ssl': True,
#         # 'verify_certs': False,
#     },
# }

# Auto update index jab model save ho
# ELASTICSEARCH_DSL_AUTO_REFRESH = True


LOGOUT_REDIRECT_URL = '/admin/login/'
LOGIN_URL = '/admin/login/'

# Production mein — real email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', '')
NEWSLETTER_FROM_NAME = os.environ.get('NEWSLETTER_FROM_NAME', 'News4Bharat')
NEWSLETTER_FROM_EMAIL = os.environ.get('NEWSLETTER_FROM_EMAIL', '')
NEWSLETTER_MAX_RECIPIENTS = int(os.environ.get('NEWSLETTER_MAX_RECIPIENTS', '300'))
NEWSLETTER_SEND_PROVIDER = os.environ.get('NEWSLETTER_SEND_PROVIDER', 'smtp').strip().lower()
NEWSLETTER_SITE_URL = os.environ.get('NEWSLETTER_SITE_URL', SEO_SITE_URL if 'SEO_SITE_URL' in globals() else 'https://news4bharat.com')
NEWSLETTER_MEDIA_BASE_URL = os.environ.get('NEWSLETTER_MEDIA_BASE_URL', '')
NEWSLETTER_LOGO_URL = os.environ.get('NEWSLETTER_LOGO_URL', 'https://news4bharat.com/assets/Logo%2002%20compact-DenhUqAp.png')
NEWSLETTER_EMBED_IMAGES = os.environ.get('NEWSLETTER_EMBED_IMAGES', 'False') == 'True'
NEWSLETTER_SMTP_HOST = os.environ.get('NEWSLETTER_SMTP_HOST', EMAIL_HOST)
NEWSLETTER_SMTP_PORT = int(os.environ.get('NEWSLETTER_SMTP_PORT', str(EMAIL_PORT or 587)))
NEWSLETTER_SMTP_USE_TLS = os.environ.get('NEWSLETTER_SMTP_USE_TLS', str(EMAIL_USE_TLS)) == 'True'
NEWSLETTER_SMTP_USER = os.environ.get('NEWSLETTER_SMTP_USER', '')
NEWSLETTER_SMTP_PASSWORD = os.environ.get('NEWSLETTER_SMTP_PASSWORD', '')
BREVO_API_KEY = os.environ.get('BREVO_API_KEY', '')
MAILERCLOUD_SMTP_HOST = os.environ.get('MAILERCLOUD_SMTP_HOST', '')
MAILERCLOUD_SMTP_PORT = int(os.environ.get('MAILERCLOUD_SMTP_PORT', '587'))
MAILERCLOUD_SMTP_USE_TLS = os.environ.get('MAILERCLOUD_SMTP_USE_TLS', 'True') == 'True'
MAILERCLOUD_SMTP_USER = os.environ.get('MAILERCLOUD_SMTP_USER', '')
MAILERCLOUD_SMTP_PASSWORD = os.environ.get('MAILERCLOUD_SMTP_PASSWORD', '')

AUTHENTICATION_BACKENDS = [
    'newsapp.backends.StaffIDBackend',
]

TEMPLATES[0]['OPTIONS']['context_processors'] += [
    'newsapp.context_processors.admin_badges',
]


GS_BUCKET_NAME = 'news4bharat-media-37'
GS_PROJECT_ID = 'news4bharat-490809'
GS_DEFAULT_ACL = None         
GS_QUERYSTRING_AUTH = False
GS_OBJECT_PARAMETERS = {
    "cache_control": "public, max-age=31536000, immutable",
}

import json
from google.oauth2 import service_account


def _normalize_gcs_service_account_payload(raw_value):
    candidate = (raw_value or "").strip()
    if not candidate:
        return None

    # Allow a file path in env for deployments that mount the JSON key as a file.
    if os.path.exists(candidate):
        with open(candidate, "r", encoding="utf-8") as handle:
            return json.load(handle)

    try:
        parsed = json.loads(candidate)
    except json.JSONDecodeError:
        parsed = None

    # Some panels store the JSON as base64 to avoid quote/newline escaping issues.
    if parsed is None:
        try:
            decoded = base64.b64decode(candidate).decode("utf-8")
            parsed = json.loads(decoded)
        except Exception:
            parsed = None

    if not isinstance(parsed, dict):
        return None

    private_key = parsed.get("private_key")
    if isinstance(private_key, str):
        parsed["private_key"] = private_key.replace("\\n", "\n").strip()

    client_email = parsed.get("client_email")
    if isinstance(client_email, str):
        parsed["client_email"] = client_email.strip()

    project_id = parsed.get("project_id")
    if isinstance(project_id, str):
        parsed["project_id"] = project_id.strip()

    return parsed


def _load_service_account_payload_from_file(file_path):
    if not file_path:
        return None
    try:
        candidate = Path(file_path)
        if not candidate.exists() or not candidate.is_file():
            return None
        with candidate.open("r", encoding="utf-8") as handle:
            parsed = json.load(handle)
        return parsed if isinstance(parsed, dict) else None
    except Exception as e:
        print(f"GCS credentials file load failed from {file_path}: {e}")
        return None

def _load_bundled_gcs_service_account_payload():
    explicit_file = BASE_DIR / "news" / "news4bharat-490809-450e05d7fce9.json"
    payload = _load_service_account_payload_from_file(explicit_file)
    if payload:
        return payload

    for candidate in sorted((BASE_DIR / "news").glob("news4bharat-490809-*.json"), reverse=True):
        payload = _load_service_account_payload_from_file(candidate)
        if payload:
            return payload
    return None


def _load_gcs_credentials():
    payload = _normalize_gcs_service_account_payload(
        os.environ.get("GCS_CREDENTIALS", "")
    )
    if not payload:
        payload = _load_service_account_payload_from_file(
            os.environ.get("GOOGLE_APPLICATION_CREDENTIALS", "")
        )
    if not payload:
        payload = _load_bundled_gcs_service_account_payload()
    if not payload:
        return None

    try:
        return service_account.Credentials.from_service_account_info(payload)
    except Exception as e:
        print(f"GCS credentials load failed: {e}")
        return None


GS_CREDENTIALS = _load_gcs_credentials()

USE_GCS_MEDIA_STORAGE = os.environ.get(
    "USE_GCS_MEDIA_STORAGE",
    "True",
).strip().lower() in {"1", "true", "yes", "on"}

if USE_GCS_MEDIA_STORAGE and GS_CREDENTIALS:
    STORAGES["default"] = {
        "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
    }
else:
    if USE_GCS_MEDIA_STORAGE and not GS_CREDENTIALS:
        print(
            "USE_GCS_MEDIA_STORAGE is enabled but valid GCS credentials were not "
            "loaded. Falling back to local FileSystemStorage."
        )
    STORAGES["default"] = {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    }

SEO_SITE_URL = os.environ.get("SEO_SITE_URL", "https://news4bharat.com").rstrip("/")
SEO_SITE_NAME = os.environ.get("SEO_SITE_NAME", "news4bharat")
SEO_GOOGLE_SA_JSON = os.environ.get("SEO_GOOGLE_SA_JSON", "").strip()

SEO_INDEXNOW_KEY = os.environ.get(
    "SEO_INDEXNOW_KEY",
    "67749d6ca24547f0877d3d9cab170641",
).strip()
SEO_INDEXNOW_ENDPOINT = os.environ.get(
    "SEO_INDEXNOW_ENDPOINT",
    "https://api.indexnow.org/indexnow",
)

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": True,
            "SOCKET_CONNECT_TIMEOUT": 0.5,
            "SOCKET_TIMEOUT": 0.5,
        }
    }
}

VAPID_PUBLIC_KEY = os.environ.get("VAPID_PUBLIC_KEY", "")
VAPID_PRIVATE_KEY = os.environ.get("VAPID_PRIVATE_KEY", "private_key.pem")
VAPID_CLAIMS = {
    "sub": f"mailto:{os.environ.get('VAPID_CLAIMS_EMAIL', 'news4bharat11@gmail.com')}"
}

GOOGLE_ANALYTICS_ID = "G-NR6G1PPS6N"  

