"""
Django settings for news project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
import os
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-7uf(u#&rj5=7ewa&5qt@9$c1*nlg^09f$hyd7t+@0)fr&+ft5p')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'newsapp',
    # 'django_crontab', 

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'news.urls'

import os

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':  [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'news.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url

DATABASES = {
    'default': dj_database_url.parse(os.environ.get('DATABASE_URL', 'postgresql://neondb_owner:npg_c9Oyqazo7jCK@ep-odd-star-a14jar0m-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require'))
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

CORS_ALLOW_ALL_ORIGINS = True

OPENWEATHER_API_KEY = "bad03cf01c063dcee90194478cda4bff"
METAL_API_KEY = "776f81dc7c1d552466ac6d57852228ea"
TWELVE_DATA_API_KEY = "6ed0b8d965e54adeb0b2d75ad62328d2"

# CRONJOBS = [
#     ('*/30 * * * *', 'yourapp.utils.fetch_and_store_metal_rates'),
# ]


# ── Elasticsearch Connection ─────────────────────────────────────────
# ELASTICSEARCH_DSL = {
#     'default': {
#         'hosts': 'http://localhost:9200',   # default ES port

#         # Agar ES 8.x use kar rahe ho aur security enabled hai:
#         # 'http_auth': ('elastic', 'your_password'),
#         # 'use_ssl': True,
#         # 'verify_certs': False,
#     },
# }

# Auto update index jab model save ho
# ELASTICSEARCH_DSL_AUTO_REFRESH = True


LOGOUT_REDIRECT_URL = '/admin/login/'
LOGIN_URL = '/admin/login/'

# Development mein — console pe dikhega
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Production mein — real email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'sheeintern@gmail.com'
EMAIL_HOST_PASSWORD = 'podu mgos mznz ljhs'

AUTHENTICATION_BACKENDS = [
    'newsapp.backends.StaffIDBackend',
]

TEMPLATES[0]['OPTIONS']['context_processors'] += [
    'newsapp.context_processors.admin_badges',
]

