# Generated by Django 6.0.2 on 2026-02-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_remove_userprofile_role_userprofile_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='newsapp.permission'),
        ),
        migrations.DeleteModel(
            name='RolePermission',
        ),
    ]
