# Generated by Django 6.0.2 on 2026-02-20 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_article_assigned_to_article_deadline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(choices=[('hero', 'Hero'), ('breaking', 'Breaking'), ('top_1', 'Top 1'), ('top_2', 'Top 2'), ('featured', 'Featured')], max_length=20, unique=True)),
                ('mode', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], default='auto', max_length=10)),
                ('auto_rule', models.CharField(blank=True, choices=[('latest', 'Latest Published'), ('most_viewed', 'Most Viewed')], max_length=20, null=True)),
                ('pin_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsapp.article')),
            ],
        ),
    ]
