# Generated by Django 6.0.2 on 2026-02-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0008_userprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetalRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_type', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver')], max_length=10)),
                ('price', models.FloatField()),
                ('change', models.FloatField(default=0)),
                ('percent_change', models.FloatField(default=0)),
                ('trend', models.CharField(default='neutral', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
