# Generated by Django 6.0.2 on 2026-02-23 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0009_metalrate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('designation', models.CharField(default='Reporter', max_length=100)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('freelancer', 'Freelancer')], default='full_time', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('assigned_categories', models.ManyToManyField(blank=True, to='newsapp.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReporterMonthlyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('articles_assigned', models.IntegerField(default=0)),
                ('articles_submitted', models.IntegerField(default=0)),
                ('articles_published', models.IntegerField(default=0)),
                ('articles_rejected', models.IntegerField(default=0)),
                ('rejection_rate', models.FloatField(default=0)),
                ('deadline_adherence_rate', models.FloatField(default=0)),
                ('avg_views', models.IntegerField(default=0)),
                ('avg_engagement_score', models.FloatField(default=0)),
                ('plagiarism_avg_score', models.FloatField(default=0)),
                ('performance_score', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reporter', 'month', 'year')},
            },
        ),
    ]
