# Generated by Django 6.0.2 on 2026-02-23 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0010_reporter_reportermonthlyperformance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReporterPerformance',
        ),
    ]
