# Generated by Django 6.0.2 on 2026-03-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0013_alter_category_options_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='category',
            name='sub_categories',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
