# Generated by Django 6.0.2 on 2026-03-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0018_message_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
