# Generated by Django 6.0.2 on 2026-03-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0019_notification_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_display_articles_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='author_display_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='author_display_linkedin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='author_display_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='article',
            name='author_display_photo',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='author_display_position',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='article',
            name='author_display_twitter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='canonical_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='focus_keyword',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='in_sitemap',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='nofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
