# Generated by Django 6.0.2 on 2026-03-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0024_userprofile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_display_reddit',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='author_display_youtube',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='sub_categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
