# Generated by Django 6.0.2 on 2026-03-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0026_article_selected_subcategories_userprofile_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_alt',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='image_source',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='secondary_keywords',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
