# Generated by Django 6.0.2 on 2026-03-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0027_article_image_alt_article_image_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sub_categories',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
