# Generated by Django 5.2.11 on 2026-03-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0029_article_scheduled_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('recipients', models.JSONField(default=list)),
                ('chosen_articles', models.JSONField(default=dict)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Newsletter Log',
                'verbose_name_plural': 'Newsletter Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
