# Generated by Django 5.2.11 on 2026-03-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0030_newsletterlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, default='email_cta', max_length=50)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'db_table': 'newsletter',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
