# Generated by Django 5.2.11 on 2026-04-15 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0035_newsletterlog_brevo_message_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageslot',
            name='ad_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage_ads/'),
        ),
        migrations.AddField(
            model_name='homepageslot',
            name='ad_image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepageslot',
            name='ad_link_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepageslot',
            name='category_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_slots', to='newsapp.category'),
        ),
        migrations.AddField(
            model_name='homepageslot',
            name='display_count',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='homepageslot',
            name='manual_articles',
            field=models.ManyToManyField(blank=True, related_name='homepage_manual_slots', to='newsapp.article'),
        ),
        migrations.AddField(
            model_name='homepageslot',
            name='overlay_article_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_overlay_slot_1', to='newsapp.article'),
        ),
        migrations.AddField(
            model_name='homepageslot',
            name='overlay_article_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_overlay_slot_2', to='newsapp.article'),
        ),
        migrations.AddField(
            model_name='homepageslot',
            name='overlay_article_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_overlay_slot_3', to='newsapp.article'),
        ),
        migrations.AlterField(
            model_name='homepageslot',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_primary_slots', to='newsapp.article'),
        ),
        migrations.AlterField(
            model_name='homepageslot',
            name='slot_name',
            field=models.CharField(choices=[('hero', 'Hero'), ('breaking', 'Breaking'), ('top_1', 'Top 1'), ('top_2', 'Top 2'), ('featured', 'Featured'), ('latest_news', 'Latest News'), ('ad_banner', 'Ad Banner')], max_length=20, unique=True),
        ),
    ]
