# Generated by Django 5.2.11 on 2026-04-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0036_homepageslot_ad_image_homepageslot_ad_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Newsletter Card',
                'verbose_name_plural': 'Newsletter Cards',
                'db_table': 'newsletter_cards',
                'ordering': ['-created_at'],
            },
        ),
    ]
