# Generated by Django 5.2.11 on 2026-04-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0038_careerapplication_contactquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettercard',
            name='chosen_articles',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='newslettercard',
            name='draft_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='newslettercard',
            name='html_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='newslettercard',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='newslettercard',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='newslettercard',
            name='image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='newslettercard',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
