# Generated by Django 5.2.11 on 2026-06-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0075_leaverequest_is_half_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='schema_types',
            field=models.CharField(blank=True, default='NewsArticle', max_length=120),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
