# Generated by Django 5.2.11 on 2026-06-18 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0076_alter_article_schema_types_alter_article_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('article', 'Article'), ('assign', 'Assignment'), ('comment', 'Comment'), ('role', 'Role'), ('message', 'Message'), ('social', 'Social'), ('category', 'Category')], max_length=20),
        ),
        migrations.CreateModel(
            name='ArticleInlineComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=64)),
                ('quoted_text', models.TextField(blank=True, default='')),
                ('body', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inline_comments', to='newsapp.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_inline_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'unique_together': {('article', 'comment_id')},
            },
        ),
    ]
